title: Math
author: Yours truly
email: manolo.bermeo@cttech.org
description: > # this means to ignore newlines until "baseurl:" 
      math, what is 2+2, quick maths, the greatest math video.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
